global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-node'
    metrics_path: /metrics
    static_configs:
      - targets: ['app-node:9001']